---
##
# The Travis CI build for this project.
##

language: python
python: "2.7"

# The tests will be run in Docker containers, to verify compatibility with
# various OSes.
sudo: required
services:
  - docker

# Each list item here will be run as a separate test by Travis CI.
env:
  - TEST_PLAY=basic_test.yml PLATFORM=ubuntu_16_04 ANSIBLE_SPEC="ansible"
  - TEST_PLAY=basic_test.yml PLATFORM=ubuntu_16_04 ANSIBLE_SPEC="ansible==2.4.0.0"
  - TEST_PLAY=basic_test.yml PLATFORM=ubuntu_14_04 ANSIBLE_SPEC="ansible"

install:
  # Generate an SSH key for use when connecting to Docker containers.
  - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa

  # Prep the Docker container that will be used.
  - ./.travis/docker_launch.sh "ansible_test_bind_dns"
  - cat ~/.ssh/id_rsa.pub | docker exec --interactive ansible_test_bind_dns.${PLATFORM} /bin/bash -c "mkdir /home/ansible_test/.ssh && cat >> /home/ansible_test/.ssh/authorized_keys"

  # Install Ansible and other required Python libraries.
  - pip install "$ANSIBLE_SPEC" && pip install -r .travis/requirements.txt
  - ansible --version
  - mkdir .travis/roles
  - ln -s `pwd` .travis/roles/karlmdavis.bind-dns

script:
  # Ensure that Ansible treats this folder as the project's base.
  - cd .travis/

  # Basic role syntax check
  - ansible-playbook $TEST_PLAY --inventory=inventory --syntax-check

  # Run the Ansible test case.
  - ansible-playbook $TEST_PLAY --inventory=inventory

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook $TEST_PLAY --inventory=inventory
    | tee /dev/tty
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

after_script:
  # Inspect the management host environment a bit post-test. Just to aid in debugging.
  - pwd
  - ls -la ../
  - ls -la ./
  - ls -la ./roles/

  # Inspect the Docker container a bit post-test. Just to aid in debugging.
  - docker exec ansible_test_bind_dns.${PLATFORM} /usr/bin/ls /etc/bind
  - docker exec ansible_test_bind_dns.${PLATFORM} /usr/bin/cat /etc/bind/named.conf.local

  # Stop all Docker containers.
  - docker stop $(docker ps -a -q)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
