---

# Install all OS packages (including Jenkins itself).
- include_tasks: "packages_{{ ansible_os_family }}.yml"

# Configure the service's launch options.
- include_tasks: "service_config_{{ ansible_os_family }}.yml"

- name: Ensure Service 'bind9' Is Running
  service:
    name: bind9
    state: started
    enabled: yes
  become: true

# If the DNS configuration has been updated, we almost always want to apply
# that immediately, as almost everything depends on DNS.
- meta: flush_handlers
